### ISSUE TITLE
Tab or Tabs not accepting custom styling

### ISSUE THREAD

**Issue by MayankShukla5031** [freeranger/react-bootstrap-tabs-demo#1]
Hi,

i am trying to apply some `css` on `tab`, tried many ways but none of them was working, kindly help me in this.

I tried these ways:

1. `<Tab label="Tab2" style={{fontSize:'14px'}}>Tab 2 content</Tab>`
2. `<Tab label="Tab2" className='tab'>Tab 2 content</Tab>`

**Comment by freeranger** [comment]
Hi,

What are you trying to style - the tab header or the tab content?

For the header, 
```html
<Tab label="Tab2" headerClass='tab'>Tab 2 content</Tab>
```
for the body:
```html
<Tab label="Tab2" contentClass='tab'>Tab 2 content</Tab>
```
You can also put these on the Tabs parent container to affect all tabs.
Look at the sample page code for various examples: https://github.com/freeranger/react-bootstrap-tabs-demo/blob/master/app/App.js

I will look at adding support for explicit style=... when I get a bit more time

**Comment by freeranger** [comment]
Tabs now accept custom styles and examples of this have been added to the demo site
